"use client"

import Head from 'next/head';
import 'swagger-ui-react/swagger-ui.css';
import SUI from 'swagger-ui-react';


export default function Index() {
  return (
    <div>
      <Head>
        <title>Swagger Doc </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SUI url="/swagger.json" />
    </div>
  );
}